apiVersion: v1
kind: ReplicationController
metadata:
  name: eureka-server
  labels:
    name: eureka-server
spec:
  replicas: 1
  selector:
    name: eureka-server
  template:
    metadata:
      labels:
        name: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: mickburgs/demo-eureka-service
        ports:
        - containerPort: 8002
          hostPort: 8002
